import Link from "next/link";

export default function Page() {
  return (
    <main style={{ padding: 28, maxWidth: 820, margin: "0 auto", display: "grid", gap: 14 }}>
      <h1 style={{ margin: 0, fontSize: 22, letterSpacing: -0.3 }}>Methodology & Sources</h1>

      <p style={{ margin: 0, opacity: 0.85 }}>
        This UI is a thin renderer over JSON outputs generated by the IPS model.
        It is a scenario simulator (not a deterministic forecast).
      </p>

      <div style={{ border: "1px solid rgba(0,0,0,0.12)", borderRadius: 16, padding: 16, display: "grid", gap: 10 }}>
        <div style={{ fontSize: 13, opacity: 0.8 }}>Where assumptions live (main repo)</div>
        <ul style={{ margin: 0, paddingLeft: 18, opacity: 0.9 }}>
          <li><code>data/parameters/core.parameters.json</code> (values + ranges + notes)</li>
          <li><code>data/scenarios/*.json</code> (scenario overrides)</li>
          <li><code>docs/</code> (model, validation, sources policy)</li>
        </ul>
      </div>

      <div style={{ border: "1px solid rgba(0,0,0,0.12)", borderRadius: 16, padding: 16, display: "grid", gap: 10 }}>
        <div style={{ fontSize: 13, opacity: 0.8 }}>What to link here</div>
        <ul style={{ margin: 0, paddingLeft: 18, opacity: 0.9 }}>
          <li>Methodology page in your main repo</li>
          <li>Sources registry</li>
          <li>“Why this might be wrong” section</li>
        </ul>
      </div>

      <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
        <div style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid rgba(0,0,0,0.12)", width: "fit-content" }}>← Back</div>
      </Link>
    </main>
  );
}
